### ISSUE TITLE
People Directory Index doesn't use last selection

### ISSUE THREAD

**Issue by jakobnotseth** [SharePoint/sp-starter-kit#219] opened 2018-12-17 09:40 UTC
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

When selecting a letter in the index, I expect the selection to filter current people in directory.

#### Observed Behavior

Selection lags one selection behind, giving the results as the previous selection.

#### Steps to Reproduce

Select letter 'B' and observe letter 'A' results (default on load), select letter 'A' and observe letter 'B' results.

#### Solution

In PeopleDirectory.tsx use index from method parameter and not from state. I.e. const selectedIndex = index and not const selectedIndex = this.state.selectedIndex in method _loadPeopleInfo

**Comment by eoverfield** [comment] 2018-12-17 16:34
@jakobnotseth great catch! That is quite correct, because of the async nature of React's setState method, we cannot be sure that state will be settled by the time we use this.state... to retrieve a state again.

Rather than update _loadPeopleInfo, I suggest instead that we change the way we re-call _loadPeopleInfo after an event. I will look to make a PR that changes our call strategy to something similar to:

```
this.setState({
  selectedIndex: index,
  searchQuery: ''
},
function() {
    // load information about people matching the selected tab
    this._loadPeopleInfo(index, null);
}
);
```

setState allows for a second optional parameter, a function that is called after state is actually set. At that point we are confident we can get the state that we set.

There is an argument that the setState callback is not preferred, rather we should use the React lifecycle and shouldComponentUpdate. I find the callback works well in these cases, and would be easier than refactoring this code at this point.

**Comment by eoverfield** [comment] 2018-12-17 19:14
@jakobnotseth addressed in PR https://github.com/SharePoint/sp-starter-kit/pull/220. If you have a moment, you might want to pull this update and see if it fixes the issue for you. In my testing, worked as expected.

**Comment by jakobnotseth** [comment] 2018-12-18 07:51
Works as expected in my tests as well :)

**Comment by bcameron1231** [comment] 2019-11-30 15:28
Closing - Fixed via #220. Confirmed by Author.

**Closed by bcameron1231** 2019-11-30 15:28 UTC
Labels: status:fixed
