### ISSUE TITLE
The customize footer missing

### ISSUE THREAD

**Issue by emailtosamit** [SharePoint/sp-starter-kit#52] opened 2018-06-25 05:47 UTC
The customize footer is not visible as demonstrated in SharePoint starter kit video 

![image](https://user-images.githubusercontent.com/17134881/41832353-0cbe979c-788f-11e8-8d36-de53022dfddb.png)

**Comment by eoverfield** [comment] 2018-06-25 07:41
I can verify the footer should appear with a clean, error free install.

Please provide any errors received during deployment. Are you able to provide any other context?

**Comment by bcameron1231** [comment] 2018-06-25 14:03
I've seen this on random occurrences. Clearing my browser cache/storage generally makes it show back up.

**Comment by gmparky** [comment] 2018-06-29 11:03
[DeployErrors.txt](https://github.com/SharePoint/sp-starter-kit/files/2149109/DeployErrors.txt)
I am having a similar issue, I have attached the errors from the script. The script is having problems with some of the commands. I have installed the latest versions of SPO Powershell and PNP. I can run some of the commands individually but they seem to depend on the context of the connection.

**Comment by eoverfield** [comment] 2018-06-29 16:19
@gmparky would you please provide the version of PnP PowerShell you have installed? A screenshot of the following command output would help.
Get-Module SharePointPnPPowerShell* -ListAvailable | Select-Object Name,Version | Sort-Object Version -Descending

**Comment by gmparky** [comment] 2018-06-29 18:35
![image](https://user-images.githubusercontent.com/40665509/42108843-973437be-7bd3-11e8-9b42-5b208cfbd38a.png)

Here you go

**Comment by eoverfield** [comment] 2018-06-29 18:40
Ah, I bet 2.23.1802.0 is taking precedence. I suggest you remove that.
Get-InstalledModule -Name "SharePointPnPPowerShellOnline" -RequiredVersion 2.23.1802.0 | Uninstall-Module

**Comment by gmparky** [comment] 2018-07-02 12:38
The command above didn't work but I removed the module deleting it from 'AppData'. 
The deploy code now runs without error and deploys the footer. Thanks for your help.

**Comment by PaoloPia** [comment] 2018-07-03 15:25
Hi @gmparky and @emailtosamit ,
Based on the previous messages I assume the issue is now fixed (thanks @eoverfield for your support). Thus, I will close this item. Please let me know if there is anything else that needs to be managed.

**Closed by PaoloPia** 2018-07-03 15:25 UTC
