### ISSUE TITLE
Is there a plan to release a version of sp-starter-kit which works in non-Targeted Release tenants?

### ISSUE THREAD

**Issue by ollij** [SharePoint/sp-starter-kit#20] opened 2018-06-10 17:50 UTC
#### Category
- [X] Question
- [ ] Bug
- [X] Enhancement

#### Expected or Desired Behavior

A version of sp-starter-kit that has as much goodness as possible - but also at the same time - works on non-Targeted Release tenants.

#### Observed Behavior

We have tried to install sp-starter-kit to few non-Targeted Release tenants and it does not seem to work. The first problem we experience is this:
Apply-PnPProvisioningTemplate : The requested operation is part of an experimental feature that is not supported in the current environment.
At C:\Users\olli\src\sp-starter-kit-master\sp-starter-kit-master\provisioning\deploy.ps1:123 char:1
+ Apply-PnPProvisioningTemplate -Path "$PSScriptRoot\portal.xml" -Param ...

#### Steps to Reproduce

Run deploy.ps1 with -TenantUrl pointing to non-Targeted Release tenant.

Thanks for your contribution! Sharing is caring.

**Comment by jstrugnell** [comment] 2018-06-11 08:15
Good question. I've already demo'd the starter kit to a client who is interested in it as a baseline Intranet. I assume it will be a few months before the current package will be compatible across standard SharePoint Online though. It would be good to know which features are (in)compatible currently.

**Comment by VesaJuvonen** [comment] 2018-06-14 06:20
In general things should work on the non-targeted release tenants, but apparently, some of the APIs which the provisioning engine is using is still supported only with the targeted release. We will investigate what exactly is the limiting factor to see if we can make the basic setup to work also in normal tenants. 

Not expecting this to be anything major, but good catch. We'll test things out to see where the issue is.

**Comment by VesaJuvonen** [comment] 2018-06-14 07:28
Currently, the problem in the package is that it's using configurations in the package-solution.json which are NOT supported yet with normal tenants. This situation will be resolved with the 1.6 release of SPFx ETA on end of July. More specifically these are related on the Graph scopes and how those are defined in the package. Right now in the short timeframe, we are NOT planning to release a separate set of packages as the overhead for doing that would be enormous for the development and operations.

In general, we do NOT recommend to use this package in your production tenants as it does deploy configurations on the tenant level - like taxonomies, Site Designs, and Site Scripts etc. You can test and demo the functionalities from other tenants - like from the dev tenants which are free for anyone from the Office 365 developer program - more details from https://developer.microsoft.com/en-us/office/dev-program.

**Closed by VesaJuvonen** 2018-06-14 07:28 UTC
