### ISSUE TITLE
World time web part not observing correct Daylight Saving from client machine

### ISSUE THREAD

**Issue by shivkumar256** [SharePoint/sp-starter-kit#242] opened 2019-01-28 06:05 UTC
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

The time for different timezone should be correct with DST calculation.

#### Observed Behavior

My timezone is (UTC+05:30) without DST and when I add a clock using webpart and set the the timezone (UTC+10:00) Canberra, Melbourne, Sydney, the clock display the incorrect time like one hour delay by actual time in Sydney. 

Since in code Clock.tsx, the DST is calculated by current timezone which needs to be corrected or DST should be calculated from selected timezone in webpart property rather than client's current timezone.

**Comment by bcameron1231** [comment] 2019-12-03 01:36
Closing - Duplicate of #193

**Closed by bcameron1231** 2019-12-03 01:36 UTC
