### ISSUE TITLE
SP-Starter-Kit - Remove hub association still shows footer on the site

### ISSUE THREAD

**Issue by prash2483** [SharePoint/sp-starter-kit#304] opened 2019-07-16 06:43 UTC
#282 ## Category
- [] Question
- [*] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

> We have installed the sp-starter-kit on our tenant and after successful installation 3 site collections has been created(1 HUB and 2 Association Sites). When I try to remove the association for one site collection the Hub Header is removed as expected from the associated site collection and similar expectation for the Hub footer.

#### Observed Behavior

When I try to remove the association for one site collection the Hub Header is removed as expected from the associated site collection but not the Hub footer(Footer still remains on the site collection).

#### Steps to Reproduce

1. After successful provision of sp-starter-kit, select one site collection in SharePoint Admin center
2. Click on "Change Hub Association" from the "Hub" Menu
3. From the left Panel select None and click on "Save"
4. Open the Site collection and the "Footer" will still remain the same.

Please help us out to resolve this issue.

Thanks,

**Comment by eoverfield** [comment] 2019-07-19 19:45
duplicate of https://github.com/SharePoint/sp-starter-kit/issues/305

**Comment by pik10** [comment] 2019-08-22 19:10
How do I remove the footer?

**Comment by bcameron1231** [comment] 2019-11-30 15:56
@pik10  You can remove the footer using PnP PowerShell using the [Remove-PnPCustomAction](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/remove-pnpcustomaction?view=sharepoint-ps) command.

An Example
`Remove-PnPCustomAction -Identity "CollabFooter"`

Closing this ticket as it was duplicate and answered in #305

**Closed by bcameron1231** 2019-11-30 15:56 UTC
Labels: Needs: Triage :mag:
