### ISSUE TITLE
Follow sites SPFx web part does not show modern team site which User has followed

### ISSUE THREAD

**Issue by gurubn** [SharePoint/sp-starter-kit#80] opened 2018-07-07 09:33 UTC
#### Category
- [x] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

Followed sites web part should show sites user has followed irrespective of whether it is classic team site/subsite, modern team site or Communication site, Please correct me if my understanding is incorrect.

#### Observed Behavior

Current Followed sites web part shows classic team site/subsite, Communication site, but It does not show modern team site. In SPFx code, It picks sites using below REST api
"_api/social.following/my/followed(types=4)", but this REST api does not list "Office 365 group connected site/modern team site".

#### Steps to Reproduce

1. Create modern team site and Follow the site 
2. Open the site where PnP Starter kit is installed in respective tenant and try to find followed modern team site

Please let me know If any more details needed!. Thank you.

#####
Thank you very much for all your effort in building PnP Starter kit. Great stuff.

**Comment by eoverfield** [comment] 2018-07-07 19:22
There does appear to be a limitation around the rest api "followed" endpoint to include group enabled (modern) team sites. I can confirm this is happening in my tenants as well. This is not a bug with the webpart though, nor can I say a bug with the api endpoint, although I would agree, the SP rest API followed endpoint should include modern team sites. @VesaJuvonen could you provide any insight?

You can view all followed sites at https://[yourtenant].sharepoint.com/_layouts/15/sharepoint.aspx?v=following. This uses an undocumented endpoint, https://[region]-sphomep.svc.ms/api/v1/, to pull a list of followed sites. There is a github issue as well as user voice entry regarding opening up this endpoint.

https://github.com/SharePoint/sp-dev-docs/issues/1689
https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/34075903-api-support-for-followed-sites

@gurubn I suggest you vote up the user voice entry if that interests you.

If the new endpoints get publicly documented by Microsoft, we can begin to safely use them. Until then, you "could" update the followed sites webpart to use the undocumented endpoint, but that is not recommended, nor would it be supported, ie. use at your own risk.

**Comment by gurubn** [comment] 2018-07-07 20:53
Thanks a lot Eric for the details and pointing me to User voice. Just now voted on it :).

At present, we are using undocumented API  "https://tenant.sharepoint.com/_vti_bin/homeapi.ashx" in one of our custom SPFx web part built to mimic Delve Following functionality ( using it from few months without any issues), but It would great If we can get publicly documented API to use.

**Comment by bcameron1231** [comment] 2019-12-03 01:19
Closing as this this a limitation of the REST API.

**Closed by bcameron1231** 2019-12-03 01:19 UTC

**Comment by stact** [comment] 2020-05-12 11:58
Hi team,

Seems that's working with chrome, not working with ie11 and edge (old one)
(unfortunately not tested with Firefox)

same url: {sitecollection}/_api/social.following/my/followedCount(types=4)
Chrome:
![image](https://user-images.githubusercontent.com/9899166/81684888-ab95ac80-9457-11ea-9ffb-e854e6b61486.png)

IE/Edge
![image](https://user-images.githubusercontent.com/9899166/81684993-db44b480-9457-11ea-8f55-cdd63c093d0b.png)
