### ISSUE TITLE
SP-Starter-Kit - Remove hub association still shows footer on the site

### ISSUE THREAD

**Issue by prash2483** [SharePoint/sp-starter-kit#305] opened 2019-07-16 06:46 UTC
#282 ## Category
- [] Question
- [*] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

> We have installed the sp-starter-kit on our tenant and after successful installation 3 site collections has been created(1 HUB and 2 Association Sites). When I try to remove the association for one site collection the Hub Header is removed as expected from the associated site collection and similar expectation for the Hub footer.

#### Observed Behavior

When I try to remove the association for one site collection the Hub Header is removed as expected from the associated site collection but not the Hub footer(Footer still remains on the site collection).

#### Steps to Reproduce

1. After successful provision of sp-starter-kit, select one site collection in SharePoint Admin center
2. Click on "Change Hub Association" from the "Hub" Menu
3. From the left Panel select None and click on "Save"
4. Open the Site collection and the "Footer" will still remain the same.

Please help us out to resolve this issue.

Thanks,
![PnPStarterKit1](https://user-images.githubusercontent.com/29190622/61271922-32064100-a7e9-11e9-9c04-f3b97cc162a5.png)

**Comment by eoverfield** [comment] 2019-07-19 19:44
This is not a bug per say, rather a feature.

The footer you are seeing is a part of the collab footer ext. You can review documentation here: https://github.com/SharePoint/sp-starter-kit/blob/master/documentation/components/ext-collab-footer.md. Disassociating from a hub will not remove this extension, thus the footer will remain.

**Comment by bcameron1231** [comment] 2019-11-30 15:51
Closing as guidance has been provided.  

Also a duplicate of #304

**Closed by bcameron1231** 2019-11-30 15:51 UTC
Labels: status:answered, status:duplicate
