### ISSUE TITLE
Issue on Recent Contact 

### ISSUE THREAD

**Issue by Rock3f** [SharePoint/sp-starter-kit#262] opened 2019-03-26 09:52 UTC
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

I would like to use recent contacts in a modern site page. After I had the webpart, I am getting this error : Access is denied. Check credentials and try again.

#### Expected or Desired Behavior

Display recent contacts

#### Observed Behavior

I tried to add rights on Graph API but I keep getting this error.

![RecentContact](https://user-images.githubusercontent.com/17547772/54987657-3b0ea080-4fb5-11e9-8694-54aa62dd0439.png)

#### Steps to Reproduce

On a modern Site Pages, add a webpart 'Recent Contacts'

Thanks a lot.

**Comment by Joy-jeevan** [comment] 2019-04-08 11:33
Even I'm having the same issue.

**Comment by MGoelles24** [comment] 2019-04-11 07:23
I'm having the same issue.

**Comment by bilalkhan870** [comment] 2019-06-30 05:59
facing the same issue ?

![Approved](https://user-images.githubusercontent.com/39082648/60392915-bbe1b900-9b1d-11e9-9a6b-25f8121ba80e.JPG)

**Comment by bilalkhan870** [comment] 2019-07-09 04:50
any updates regarding 

Recent Contacts 
--------------------------------------------

Access is denied. Check credentials and try again.


![](https://user-images.githubusercontent.com/39082648/60392915-bbe1b900-9b1d-11e9-9a6b-25f8121ba80e.JPG)


@VesaJuvonen 
@waldekmastykarz

**Comment by gallantdon** [comment] 2019-08-02 17:42
I am also having this issue.

**Comment by bcameron1231** [comment] 2019-11-30 15:14
Hi Everyone,

Can any of you confirm if this is still happening to you? I'm unable to reproduce the issue on my end. As it's an older ticket, I'd love to close this out if it's not an issue for you any longer.

**Closed** 2019-12-14 16:00 UTC
Labels: Needs: Author Feedback, no-recent-activity

**Comment by tienou** [comment] 2020-05-29 11:04
Hello,



> Hi Everyone,
> 
> Can any of you confirm if this is still happening to you?

Yes I confirm
